---
- name: Setup student accounts for magnum on bastion
  hosts: localhost
  connection: local
  become: yes

  tasks:
  - name: Create student accounts
    user:
      name: "{{ item }}"
      password: "{{ lookup('password', 'credentials/' + item + '/password.txt encrypt=md5_crypt') }}"
      state: present
    with_sequence: start=0 end=1 format=student%02x
