---
- name: Setup student accounts for magnum on bastion
  hosts: localhost
  connection: local

  tasks:
  - name: Create student accounts
    become: yes
    user:
      name: "student{{ item }}"
      password: "{{ lookup('password', 'credentials/' + item + '/password.txt encrypt=md5_crypt') }}"
      state: present
    with_sequence: start=0 end=40

  - name: Create student namespace
    shell: kubectl create namespace student{{ item }}
    #with_sequence: start=0 end=40 format=student%02x
    with_sequence: start=0 end=40
