---
- name: Setup student accounts on OpenStack
  hosts: localhost
  connection: local

  tasks:
  - name: Get password from credentials file
    shell: pwd=`cat credentials/{{ item }}/password.txt |awk {'print $1'}`; openstack user create --password $pwd student{{ item }}
    with_sequence: start=0 end=40
