---
- name: Remove student accounts for magnum on bastion
  hosts: localhost
  connection: local

  tasks:
  - name: Delete student accounts
    become: yes
    user:
      name: student{{ item }}
      state: absent
    with_sequence: start=0 end=40
